In [1]:
import numpy as np

DATATYPES AND ATTRIBUTES

In [4]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [2]:
a1=np.array([[1,2,3],[2,3,4],[5,6,7]])
a1

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [3]:
a1.ndim

2

# 

In [4]:
a1.size

9

In [5]:
import pandas as pd
df=pd.DataFrame(a1)
df

0  1  2
0  1  2  3
1  2  3  4
2  5  6  7

In [6]:
arr = np.ones((2,3))

In [7]:
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr1 = np.zeros((2,3))

In [10]:
arr1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr2 = np.arange(2,20,2)
arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.random.seed(seed = 9)
arr3 = np.random.randint(0,15,size=(3,4))
arr3

array([[14, 12, 14,  5],
       [ 6,  8, 11,  6],
       [13,  1,  6,  4]])

In [19]:
arr4 = np.random.random((3,3))
arr4

array([[0.77151543, 0.04535324, 0.34140605],
       [0.85481515, 0.50319717, 0.50075284],
       [0.86919864, 0.81176292, 0.41497297]])

In [17]:
#CREATE NUMPY ARRAY WITH TWO RANGES AND ARRANGE IN MATRIX FORMAT
X,Y = np.mgrid[5:50:5, 6:60:6]
arr5 = np.vstack((X.flatten(), Y.flatten())).T
arr5

array([[ 5,  6],
       [ 5, 12],
       [ 5, 18],
       [ 5, 24],
       [ 5, 30],
       [ 5, 36],
       [ 5, 42],
       [ 5, 48],
       [ 5, 54],
       [10,  6],
       [10, 12],
       [10, 18],
       [10, 24],
       [10, 30],
       [10, 36],
       [10, 42],
       [10, 48],
       [10, 54],
       [15,  6],
       [15, 12],
       [15, 18],
       [15, 24],
       [15, 30],
       [15, 36],
       [15, 42],
       [15, 48],
       [15, 54],
       [20,  6],
       [20, 12],
       [20, 18],
       [20, 24],
       [20, 30],
       [20, 36],
       [20, 42],
       [20, 48],
       [20, 54],
       [25,  6],
       [25, 12],
       [25, 18],
       [25, 24],
       [25, 30],
       [25, 36],
       [25, 42],
       [25, 48],
       [25, 54],
       [30,  6],
       [30, 12],
       [30, 18],
       [30, 24],
       [30, 30],
       [30, 36],
       [30, 42],
       [30, 48],
       [30, 54],
       [35,  6],
       [35, 12],
       [35, 18],
       [35, 24],
       [35, 30

VIEW ARRAYS AND MATRICES

In [23]:
np.random.seed(seed = 1)
arr6 = np.random.randint(1,10, size=(3,3,3))
arr6

array([[[6, 9, 6],
        [1, 1, 2],
        [8, 7, 3]],

       [[5, 6, 3],
        [5, 3, 5],
        [8, 8, 2]],

       [[8, 1, 7],
        [8, 7, 2],
        [1, 2, 9]]])

In [24]:
arr6[:2,:2,:2]

array([[[6, 9],
        [1, 1]],

       [[5, 6],
        [5, 3]]])

In [25]:
arr6

array([[[6, 9, 6],
        [1, 1, 2],
        [8, 7, 3]],

       [[5, 6, 3],
        [5, 3, 5],
        [8, 8, 2]],

       [[8, 1, 7],
        [8, 7, 2],
        [1, 2, 9]]])

In [30]:
arr6.shape

(3, 3, 3)

MANIPULATING ARRAYS

In [31]:
a1=np.array([1,2,4])
a2 = np.ones(3)
a1
a2

array([1., 1., 1.])

In [33]:
a1

array([1, 2, 4])

In [34]:
a1+a2

array([2., 3., 5.])

In [35]:
a1*a2

array([1., 2., 4.])

In [36]:
np.sum(a1)

7

In [38]:
arr7 = np.random.random((3,3))
arr7

array([[0.82960336, 0.27304997, 0.0592432 ],
       [0.67052804, 0.59306552, 0.6716541 ],
       [0.41178788, 0.1975509 , 0.28962964]])

In [39]:
%timeit np.sum(arr7)

4.48 µs ± 384 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [3]:
a1

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [6]:
a1.reshape(3,3,1)

array([[[1],
        [2],
        [3]],

       [[2],
        [3],
        [4]],

       [[5],
        [6],
        [7]]])

In [8]:
a1.reshape(3,3,1).T

array([[[1, 2, 5],
        [2, 3, 6],
        [3, 4, 7]]])

In [9]:
x=np.random.randint(1,10,size=(3,2))
x

array([[9, 5],
       [5, 9],
       [3, 7]])

In [10]:
y=np.random.randint(1,10,size=(3,2))
y

array([[3, 6],
       [2, 4],
       [4, 2]])

In [11]:
np.dot(x,y)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [12]:
np.dot(x,y.T)

array([[57, 38, 46],
       [69, 46, 38],
       [51, 34, 26]])

In [17]:
import pandas as pd
np.random.seed(1)
sales_amount=np.random.randint(1,20,size=(5,3))
weekly_butter_sales=pd.DataFrame(sales_amount,index=["Mon","Tue","Wed","Thu","Fri"],columns=["Almond","Peanut","Cashew"])
weekly_butter_sales

Almond  Peanut  Cashew
Mon       6      12      13
Tue       9      10      12
Wed       6      16       1
Thu      17       2      13
Fri       8      14       7

In [21]:
np.random.seed(2)
sales_price=np.random.randint(10,30,size=(1,3))

total_price_daily=np.dot(sales_amount,sales_price.T)
sales_price

array([[18, 25, 23]])

In [22]:
total_price_daily

array([[707],
       [688],
       [531],
       [655],
       [655]])

In [41]:
#weekly_butter_sales["Total Price"]=pd.Series(total_price_daily.reshape(1,5))
#total_price_daily=pd.Series(total_price_daily.reshape(5))

indexOfSeries=["Mon","Tue","Wed","Thu","Fri"]

total_price_daily.index=indexOfSeries
total_price_daily

Mon    707
Tue    688
Wed    531
Thu    655
Fri    655
dtype: int32

In [42]:
weekly_butter_sales["Total Price"]=total_price_daily

In [43]:
weekly_butter_sales

Almond  Peanut  Cashew  Total Price
Mon       6      12      13          707
Tue       9      10      12          688
Wed       6      16       1          531
Thu      17       2      13          655
Fri       8      14       7          655

# TURN IMAGE INTO NUMPY ARRAY

In [2]:
from matplotlib.image import imread
panda=imread("numpy-images/panda.png")

In [3]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [4]:
panda.shape

(2330, 3500, 3)

In [5]:
panda.ndim

3

In [6]:
panda.size

24465000

In [7]:
car=imread("numpy-images/car-photo.png")
car.shape

(431, 575, 4)

In [8]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352