# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [6]:
# Create a 1-dimensional NumPy array using np.array()
a1=np.array([1,2,3])


# Create a 2-dimensional NumPy array using np.array()
a2=np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape ,a1.ndim, a1.dtype, type(a1)

((3,), 1, dtype('int32'), numpy.ndarray)

In [7]:
# Attributes of 2-dimensional array
a2.shape ,a2.ndim, a2.dtype, type(a2)

((2, 3), 2, dtype('int32'), numpy.ndarray)

In [8]:
# Attributes of 3-dimensional array
a3.shape ,a3.ndim, a3.dtype, type(a3)

((3, 2, 3), 3, dtype('int32'), numpy.ndarray)

In [10]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df=pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [12]:
# Create an array of shape (10, 2) with only ones
arr1=np.ones((10,2))
arr1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
# Create an array of shape (7, 2, 3) of only zeros
arr2=np.zeros((7,2,3))
arr2

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
# Create an array within a range of 0 and 100 with step 3
arr3=np.arange(0,100,3)
arr3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [15]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr4=np.random.randint(0,10,size=(7,2))
arr4

array([[7, 4],
       [4, 6],
       [8, 0],
       [9, 5],
       [6, 8],
       [9, 3],
       [8, 3]])

In [16]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr5=np.random.random(size=(3,5))
arr5

array([[0.73629666, 0.35919331, 0.14274991, 0.36679823, 0.57820188],
       [0.34525764, 0.7575382 , 0.63397019, 0.10383113, 0.48738496],
       [0.21761605, 0.68471695, 0.86638714, 0.04480986, 0.87869835]])

In [18]:
# Set the random seed to 42
np.random.seed(seed=42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr6=np.random.randint(0,10,size=(4,6))
arr6

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [20]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
np.random.seed(seed=1)
arr7=np.random.randint(1,10,size=(3,7))

# Find the unique numbers in the array you just created
np.unique(arr7)

array([1, 2, 3, 5, 6, 7, 8, 9])

In [21]:
# Find the 0'th index of the latest array you created
arr7[0]

array([6, 9, 6, 1, 1, 2, 8])

In [22]:
# Get the first 2 rows of latest array you created
arr7[:2]

array([[6, 9, 6, 1, 1, 2, 8],
       [7, 3, 5, 6, 3, 5, 3]])

In [24]:
# Get the first 2 values of the first 2 rows of the latest array
arr7[:2,:2]

array([[6, 9],
       [7, 3]])

In [26]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr8=np.random.randint(0,10,size=(3,5))
arr9=np.ones((3,5))

In [27]:
# Add the two arrays together
arr8+arr9

array([[10., 10.,  8.,  7., 10.],
       [ 2.,  1.,  2.,  9.,  9.],
       [ 4., 10.,  9.,  8.,  4.]])

In [28]:
# Create another array of ones of shape (5, 3)
arr10=np.ones((5,3))

In [29]:
# Try add the array of ones and the other most recent array together
arr8+arr9+arr10

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [30]:
# Create another array of ones of shape (3, 5)
arr11=np.ones((3,5))

In [32]:
# Subtract the new array of ones from the other most recent array
arr12=arr8+arr9-arr11

In [35]:
# Multiply the ones array with the latest array
arr13=np.dot(arr12,arr10)

In [36]:
# Take the latest array to the power of 2 using '**'
arr13**2

array([[1600., 1600., 1600.],
       [ 324.,  324.,  324.],
       [ 900.,  900.,  900.]])

In [37]:
# Do the same thing with np.square()
np.square(arr13)

array([[1600., 1600., 1600.],
       [ 324.,  324.,  324.],
       [ 900.,  900.,  900.]])

In [38]:
# Find the mean of the latest array using np.mean()
np.mean(arr13)

29.333333333333332

In [39]:
# Find the maximum of the latest array using np.max()
np.max(arr13)

40.0

In [40]:
# Find the minimum of the latest array using np.min()
np.min(arr13)

18.0

In [41]:
# Find the standard deviation of the latest array
np.std(arr13)

8.993825042154695

In [42]:
# Find the variance of the latest array
np.var(arr13)

80.8888888888889

In [45]:
# Reshape the latest array to (3, 5, 1)
arr12.reshape(3,5,1)
arr12.shape

(3, 5)

In [46]:
# Transpose the latest array
arr13.T

array([[40., 18., 30.],
       [40., 18., 30.],
       [40., 18., 30.]])

What does the transpose do?

In [48]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr14=np.random.randint(0,10,size=(3,3))
arr15=np.random.randint(0,10,size=(3,2))

In [49]:
# Perform a dot product on the two newest arrays you created
np.dot(arr14,arr15)

array([[45, 32],
       [27, 49],
       [ 9, 42]])

In [35]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)


In [36]:
# Perform a dot product on the two newest arrays you created


It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [51]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr16=np.random.randint(0,10,size=(3,3))
arr17=np.random.randint(0,10,size=(3,3))

In [52]:
# Compare the two arrays with '>'
arr16

array([[9, 2, 7],
       [7, 9, 8],
       [6, 9, 3]])

What happens when you compare the arrays with `>`?

In [53]:
# Compare the two arrays with '>='
arr17

array([[7, 7, 4],
       [5, 9, 3],
       [6, 8, 0]])

In [54]:
# Find which elements of the first array are greater than 7
arr16>arr17

array([[ True, False,  True],
       [ True, False,  True],
       [False,  True,  True]])

In [55]:
# Which parts of each array are equal? (try using '==')
arr16==arr17

array([[False, False, False],
       [False,  True, False],
       [ True, False, False]])

In [57]:
# Sort one of the arrays you just created in ascending order
arr16.sort()
arr16

array([[2, 7, 9],
       [7, 8, 9],
       [3, 6, 9]])

In [58]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr16)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [59]:
# Find the index with the maximum value in one of the arrays you've created
np.argmin(arr17)

8

In [60]:
# Find the index with the minimum value in one of the arrays you've created
np.argmax(arr17)

4

In [61]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr17,axis=1)

array([0, 1, 1], dtype=int64)

In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [65]:
# Create an array of normally distributed random numbers
rng = np.random.default_rng()
rng.normal(size=(2, 4))

array([[-0.3942328 ,  1.20065837, -0.07788814,  1.12649887],
       [-1.53210495, -1.04598312,  0.37147149,  2.09272508]])

In [63]:
# Create an array with 10 evenly spaced numbers between 1 and 100
arr18=np.arange(0,100,10)
arr18

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.